# Generated by Django 3.2.18 on 2023-05-21 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artista1', to='peliculas.artistas')),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128, verbose_name='Titulo')),
                ('estreno', models.CharField(default=None, max_length=4, null=True, verbose_name='Estreno')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
                ('resumen', models.TextField(null=True, verbose_name='Resumen')),
                ('artistas', models.ManyToManyField(through='peliculas.Elenco', to='peliculas.Artistas')),
                ('director', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='director', to='peliculas.artistas')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.generos')),
            ],
        ),
        migrations.AddField(
            model_name='elenco',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.peliculas'),
        ),
    ]
