# Generated by Django 3.2.18 on 2023-04-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'generos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('estreno', models.IntegerField()),
                ('id_genero', models.IntegerField(db_column='Id_genero')),
                ('director', models.IntegerField(db_column='Id_director')),
                ('id_artista1', models.IntegerField(db_column='Id_artista1')),
                ('id_artista2', models.IntegerField(db_column='Id_artista2')),
                ('id_artista3', models.IntegerField(db_column='Id_artista3')),
                ('portada', models.CharField(max_length=255)),
                ('resumen', models.TextField()),
            ],
            options={
                'db_table': 'peliculas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
    ]
