# Generated by Django 3.2.18 on 2023-06-01 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('icono', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
            ],
        ),
        migrations.AlterField(
            model_name='elenco',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.artistas'),
        ),
        migrations.CreateModel(
            name='Donde_ver_pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.peliculas')),
                ('plataformas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.plataformas')),
            ],
        ),
        migrations.AddField(
            model_name='peliculas',
            name='plataformas',
            field=models.ManyToManyField(through='peliculas.Donde_ver_pelicula', to='peliculas.Plataformas'),
        ),
    ]
