# Generated by Django 3.2.18 on 2023-06-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_auto_20230601_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donde_ver_pelicula',
            old_name='plataformas',
            new_name='plataforma',
        ),
    ]
