# Generated by Django 4.1.3 on 2023-06-05 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Donde_ver_pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('icono', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128, verbose_name='Titulo')),
                ('estreno', models.CharField(default=None, max_length=4, null=True, verbose_name='Estreno')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
                ('resumen', models.TextField(null=True, verbose_name='Resumen')),
                ('artistas', models.ManyToManyField(through='administracion.Elenco', to='administracion.artista')),
                ('director', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='director', to='administracion.artista')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.genero')),
                ('plataformas', models.ManyToManyField(through='administracion.Donde_ver_pelicula', to='administracion.plataforma')),
            ],
        ),
        migrations.AddField(
            model_name='elenco',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.pelicula'),
        ),
        migrations.AddField(
            model_name='donde_ver_pelicula',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.pelicula'),
        ),
        migrations.AddField(
            model_name='donde_ver_pelicula',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.plataforma'),
        ),
    ]
