# Generated by Django 3.2.18 on 2023-06-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='portada_grande',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada_grande'),
        ),
    ]
