# Generated by Django 3.2.18 on 2023-06-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_pelicula_portada_grande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.IntegerField(verbose_name='pelicula_id')),
                ('puntaje', models.IntegerField(verbose_name='puntaje')),
                ('usuario', models.IntegerField(verbose_name='usuario')),
            ],
        ),
    ]
