from django.shortcuts import render

# Create your views here.
def index(request):
    base_peliculas = [
        {
            'titulo' : 'Atrapame si puedes',
            'estreno':'2002',
            'Id_genero':'3',
            'Id_director':'78',
            'Id_artista1':'56',    
            'Id_artista2':'81',  
            'Id_artista3':'20',  
            'portada':'1.jpg',
            'resumen':'Un veterano agente del FBI le sigue la pista a Frank Abagnale Jr., quien antes de cumplir 19 años ha forjado millones de dólares en cheques haciéndose pasar por piloto, doctor y abogado.',
            'Id_user':'1',
        },

        {
            'titulo':'Blade Runner',
            'estreno':'1982',
            'Id_genero':'4',
            'Id_director':'69',
            'Id_artista1':'33',    
            'Id_artista2':'75',  
            'Id_artista3':'77',  
            'portada':'2.jpg',
            'resumen':'Un blade runner debe encontrar y retirar a cuatro replicantes que robaron una nave en el espacio y han regresado a la Tierra para encontrar a su creador.',
            'Id_user':'1' ,
        },

        {
            'titulo':'Diamantes de Sangre',
            'estreno':'2006',
            'Id_genero':'4',
            'Id_director':'26',
            'Id_artista1':'56',    
            'Id_artista2':'24',  
            'Id_artista3':'40',  
            'portada':'3.jpg',
            'resumen':'Un pescador, un traficante y un hombre de negocios se enfrentar por tomar posesión del diamante más preciado.',
            'Id_user':'1',      
        },

        {
            'titulo':'Duro de Matar',
            'estreno':'1988',
            'Id_genero':'1',
            'Id_director':'45',
            'Id_artista1':'12',    
            'Id_artista2':'1',  
            'Id_artista3':'11',  
            'portada':'4.jpg',
            'resumen':'John McClane, agente del departamento de policía de Nueva York, intenta salvar a su mujer, Holly Gennaro, y a otras personas a las que el terrorista alemán, Hans Gruber, ha tomado como rehenes durante la fiesta navideña en el Nakatomi Plaza en Los Ángeles.',
            'Id_user':'1', 
        },

        {
            'titulo':'Gladiador',
            'estreno':'2000',
            'Id_genero':'6',
            'Id_director':'69',
            'Id_artista1':'74',    
            'Id_artista2':'42',  
            'Id_artista3':'21',  
            'portada':'5.jpg',
            'resumen':'Un general romano se propone vengarse del corrupto emperador que asesinó a su familia y lo convirtió en esclavo.',
            'Id_user':'1',      
        },

        {
            'titulo':'El Grinch',
            'estreno':'2000',
            'Id_genero':'4',
            'Id_director':'73',
            'Id_artista1':'41',    
            'Id_artista2':'79',  
            'Id_artista3':'51',  
            'portada':'6.jpg',
            'resumen':'A las afueras de Whoville vive un Grinch verde sediento de venganza que planea arruinar las Navidades para todos los habitantes de la ciudad.',
            'Id_user':'1',      
        },

        {
            'titulo':'El lobo de Wall Street',
            'estreno':'2013',
            'Id_genero':'2',
            'Id_director':'60',
            'Id_artista1':'56',    
            'Id_artista2':'47',  
            'Id_artista3':'59',  
            'portada':'7.jpg',
            'resumen':'Basado en la historia real de Jordan Belfort, desde su ascenso a convertirse en un adinerado agente de bolsa viviendo la gran vida hasta su caída, que involucra el crimen, la corrupción y el gobierno federal.',
            'Id_user':'1',      
        },

        {
            'titulo':'El Renacido',
            'estreno':'2015',
            'Id_genero':'6',
            'Id_director':'2',
            'Id_artista1':'56',    
            'Id_artista2':'82',  
            'Id_artista3':'83',  
            'portada':'8.jpg',
            'resumen':'En 1820, un hombre parte de una expedición de comerciantes de pieles lucha por sobrevivir cuando sus compañeros le abandonan y dan por muerto tras ser mutilado por un oso.',
            'Id_user':'1',   
        },

        {
            'titulo':'Gambito de Dama',
            'estreno':'2020',
            'Id_genero':'6',
            'Id_director':'76',
            'Id_artista1':'6',    
            'Id_artista2':'16',  
            'Id_artista3':'9',  
            'portada':'9.jpg',
            'resumen':'Ambientada en la Guerra Fría, una huérfana llamada Beth Harmon con un don para el ajedrez lucha contra las adicciones mientras intenta ser la mejor jugadora del mundo.',
            'Id_user':'1',      
        },

        {
            'titulo':'Joker',
            'estreno':'2019',
            'Id_genero':'6',
            'Id_director':'80',
            'Id_artista1':'42',    
            'Id_artista2':'70',  
            'Id_artista3':'85',  
            'portada':'10.jpg',
            'resumen':'En Gotham, Arthur Fleck, un comediante con problemas de salud mental, es marginado y maltratado por la sociedad. Se adentra en una espiral de crimen que resulta revolucionaria. Pronto conoce a su alter-ego, el Joker.',
            'Id_user':'1',      
        },

        {
            'titulo':'John Wick',
            'estreno':'2014',
            'Id_genero':'1',
            'Id_director':'14',
            'Id_artista1':'50',    
            'Id_artista2':'62',  
            'Id_artista3':'3',  
            'portada':'11.jpg',
            'resumen':'Un ex asesino a sueldo suspende su jubilación para localizar a los mafiosos que mataron a su perro y le quitaron todo.',
            'Id_user':'1',      
        },
    ]
    listado_peliculas = [
        {
            'titulo' : 'Atrapame si puedes',
            'estreno':'2002',
            'Id_genero':'3',
            'Id_director':'78',
            'Id_artista1':'56',    
            'Id_artista2':'81',  
            'Id_artista3':'20',  
            'portada':'1.jpg',
            'resumen':'Un veterano agente del FBI le sigue la pista a Frank Abagnale Jr., quien antes de cumplir 19 años ha forjado millones de dólares en cheques haciéndose pasar por piloto, doctor y abogado.',
            'Id_user':'1',
        },

        {
            'titulo':'Blade Runner',
            'estreno':'1982',
            'Id_genero':'4',
            'Id_director':'69',
            'Id_artista1':'33',    
            'Id_artista2':'75',  
            'Id_artista3':'77',  
            'portada':'2.jpg',
            'resumen':'Un blade runner debe encontrar y retirar a cuatro replicantes que robaron una nave en el espacio y han regresado a la Tierra para encontrar a su creador.',
            'Id_user':'1' ,
        },

        {
            'titulo':'Diamantes de Sangre',
            'estreno':'2006',
            'Id_genero':'4',
            'Id_director':'26',
            'Id_artista1':'56',    
            'Id_artista2':'24',  
            'Id_artista3':'40',  
            'portada':'3.jpg',
            'resumen':'Un pescador, un traficante y un hombre de negocios se enfrentar por tomar posesión del diamante más preciado.',
            'Id_user':'1',      
        },

        {
            'titulo':'Duro de Matar',
            'estreno':'1988',
            'Id_genero':'1',
            'Id_director':'45',
            'Id_artista1':'12',    
            'Id_artista2':'1',  
            'Id_artista3':'11',  
            'portada':'4.jpg',
            'resumen':'John McClane, agente del departamento de policía de Nueva York, intenta salvar a su mujer, Holly Gennaro, y a otras personas a las que el terrorista alemán, Hans Gruber, ha tomado como rehenes durante la fiesta navideña en el Nakatomi Plaza en Los Ángeles.',
            'Id_user':'1', 
        },

        {
            'titulo':'Gladiador',
            'estreno':'2000',
            'Id_genero':'6',
            'Id_director':'69',
            'Id_artista1':'74',    
            'Id_artista2':'42',  
            'Id_artista3':'21',  
            'portada':'5.jpg',
            'resumen':'Un general romano se propone vengarse del corrupto emperador que asesinó a su familia y lo convirtió en esclavo.',
            'Id_user':'1',      
        },

        {
            'titulo':'El Grinch',
            'estreno':'2000',
            'Id_genero':'4',
            'Id_director':'73',
            'Id_artista1':'41',    
            'Id_artista2':'79',  
            'Id_artista3':'51',  
            'portada':'6.jpg',
            'resumen':'A las afueras de Whoville vive un Grinch verde sediento de venganza que planea arruinar las Navidades para todos los habitantes de la ciudad.',
            'Id_user':'1',      
        },

        {
            'titulo':'El lobo de Wall Street',
            'estreno':'2013',
            'Id_genero':'2',
            'Id_director':'60',
            'Id_artista1':'56',    
            'Id_artista2':'47',  
            'Id_artista3':'59',  
            'portada':'7.jpg',
            'resumen':'Basado en la historia real de Jordan Belfort, desde su ascenso a convertirse en un adinerado agente de bolsa viviendo la gran vida hasta su caída, que involucra el crimen, la corrupción y el gobierno federal.',
            'Id_user':'1',      
        },

        {
            'titulo':'El Renacido',
            'estreno':'2015',
            'Id_genero':'6',
            'Id_director':'2',
            'Id_artista1':'56',    
            'Id_artista2':'82',  
            'Id_artista3':'83',  
            'portada':'8.jpg',
            'resumen':'En 1820, un hombre parte de una expedición de comerciantes de pieles lucha por sobrevivir cuando sus compañeros le abandonan y dan por muerto tras ser mutilado por un oso.',
            'Id_user':'1',   
        },

        {
            'titulo':'Gambito de Dama',
            'estreno':'2020',
            'Id_genero':'6',
            'Id_director':'76',
            'Id_artista1':'6',    
            'Id_artista2':'16',  
            'Id_artista3':'9',  
            'portada':'9.jpg',
            'resumen':'Ambientada en la Guerra Fría, una huérfana llamada Beth Harmon con un don para el ajedrez lucha contra las adicciones mientras intenta ser la mejor jugadora del mundo.',
            'Id_user':'1',      
        },

        {
            'titulo':'Joker',
            'estreno':'2019',
            'Id_genero':'6',
            'Id_director':'80',
            'Id_artista1':'42',    
            'Id_artista2':'70',  
            'Id_artista3':'85',  
            'portada':'10.jpg',
            'resumen':'En Gotham, Arthur Fleck, un comediante con problemas de salud mental, es marginado y maltratado por la sociedad. Se adentra en una espiral de crimen que resulta revolucionaria. Pronto conoce a su alter-ego, el Joker.',
            'Id_user':'1',      
        },

        {
            'titulo':'John Wick',
            'estreno':'2014',
            'Id_genero':'1',
            'Id_director':'14',
            'Id_artista1':'50',    
            'Id_artista2':'62',  
            'Id_artista3':'3',  
            'portada':'11.jpg',
            'resumen':'Un ex asesino a sueldo suspende su jubilación para localizar a los mafiosos que mataron a su perro y le quitaron todo.',
            'Id_user':'1',      
        },
    ]
    context={
            'titulo' : 'Atrapame si puedes',
            'estreno':'2002',
            'Id_genero':'3',
            'Id_director':'78',
            'Id_artista1':'56',    
            'Id_artista2':'81',  
            'Id_artista3':'20',  
            'portada':'1.jpg',
            'resumen':'Un veterano agente del FBI le sigue la pista a Frank Abagnale Jr., quien antes de cumplir 19 años ha forjado millones de dólares en cheques haciéndose pasar por piloto, doctor y abogado.',
            'Id_user':'1',
            'pelis': base_peliculas,
            'listado_peliculas' : listado_peliculas
            }
    return render(request, 'peliculas/welcome.html', context)
           
